const leagues=[
 {id:'j1',sport:'football',country:'日本',flag:'🇯🇵',name:'J1リーグ',short:'J1'},
 {id:'premier-league',sport:'football',country:'イングランド',flag:'🏴',name:'Premier League',short:'PL'},
 {id:'laliga',sport:'football',country:'スペイン',flag:'🇪🇸',name:'La Liga',short:'LL'},
 {id:'seriea',sport:'football',country:'イタリア',flag:'🇮🇹',name:'Serie A',short:'SA'},
 {id:'bundesliga',sport:'football',country:'ドイツ',flag:'🇩🇪',name:'Bundesliga',short:'BL'},
 {id:'ligue1',sport:'football',country:'フランス',flag:'🇫🇷',name:'Ligue 1',short:'L1'},
 {id:'mls',sport:'football',country:'アメリカ',flag:'🇺🇸',name:'MLS',short:'MLS'},
 {id:'mlb',sport:'baseball',country:'アメリカ',flag:'🇺🇸',name:'MLB',short:'MLB'}];
let sport='football',selected=null,data=null,mlbFilter='all';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function renderLeagues(){const list=leagues.filter(x=>x.sport===sport);$('#league-title').textContent=sport==='football'?'サッカーリーグ':'野球リーグ';$('#league-grid').innerHTML=list.map(l=>`<button class="league-card" data-id="${l.id}"><span class="flag">${l.flag}</span><small>${l.country}</small><strong>${l.name}</strong><span class="arrow">→</span></button>`).join('');$$('.league-card').forEach(b=>b.onclick=()=>openLeague(b.dataset.id));}
function renderQuick(){const fav=JSON.parse(localStorage.getItem('wt-favorites')||'[]'),last=localStorage.getItem('wt-last');const ids=[...new Set([...fav,last].filter(Boolean))];if(!ids.length)return;$('#quick').classList.remove('hidden');$('#quick').innerHTML=`<h2>クイックアクセス</h2><div class="quick-list">${ids.map(id=>{const l=leagues.find(x=>x.id===id);return l?`<button class="chip" data-id="${id}">${fav.includes(id)?'★ ': '前回：'}${l.name}</button>`:''}).join('')}</div>`;$$('#quick button').forEach(b=>b.onclick=()=>openLeague(b.dataset.id));}
async function openLeague(id){selected=leagues.find(x=>x.id===id);localStorage.setItem('wt-last',id);try{const r=await fetch(`data/${id}.json?d=${new Date().toISOString().slice(0,10)}`);if(!r.ok)throw 0;data=await r.json()}catch{data={status:'error',teams:[],updatedAt:null,error:'最新順位を取得できませんでした'}}$('.browser').classList.add('hidden');$('#standings').classList.remove('hidden');$('#flag').textContent=selected.flag;$('#country').textContent=data.country||selected.country;$('#selected-title').textContent=data.leagueName||selected.name;$('#league-badge').textContent=selected.short;$('#season').textContent=data.season?`シーズン：${data.season}`:'シーズン情報なし';$('#updated').textContent=`最終更新：${fmtDate(data.updatedAt)}`;const failed=data.status!=='ok'||data.stale;$('#notice').classList.toggle('hidden',!failed);$('#notice').textContent=data.stale?'最新データ取得失敗・前回のデータを表示中':(data.error||'最新順位を取得できませんでした');setFavorite();renderTable();window.scrollTo({top:document.querySelector('main').offsetTop,behavior:'smooth'});}
function fmtDate(x){if(!x)return '--';return new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Tokyo'}).format(new Date(x));}
function renderTable(){if(selected.sport==='baseball')renderBaseball();else renderFootball();}
function mv(t){const n=t.movement||0;return `<span class="movement ${n>0?'up':n<0?'down':''}">${n>0?'↑ '+n:n<0?'↓ '+Math.abs(n):'—'}</span>`}
function logo(t){return `<img src="${t.logo||'data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs='}" alt="" loading="lazy" onerror="this.style.visibility='hidden'">`}
function renderFootball(){const ts=data.teams||[];$('#filters').classList.add('hidden');$('#thead').innerHTML='<tr><th class="pos">順位</th><th class="team">チーム</th><th>変動</th><th>試合</th><th class="optional">勝</th><th class="optional">分</th><th class="optional">敗</th><th class="optional">得点</th><th class="optional">失点</th><th>得失差</th><th>勝点</th></tr>';$('#tbody').innerHTML=ts.map((t,i)=>`<tr class="${i<3?'top3 ':''}${t.description&&/relegation/i.test(t.description)?'relegation':''}"><td class="pos">${t.rank}</td><td class="team"><span class="team-cell">${logo(t)}${t.name}</span></td><td>${mv(t)}</td><td>${t.played}</td><td class="optional">${t.won}</td><td class="optional">${t.draw}</td><td class="optional">${t.lost}</td><td class="optional">${t.gf}</td><td class="optional">${t.ga}</td><td>${t.gd>0?'+':''}${t.gd}</td><td class="points">${t.points}</td></tr>`).join('')||'<tr><td colspan="11">最新順位を取得できませんでした</td></tr>';}
function renderBaseball(){const all=data.teams||[];const groups=['all',...new Set(all.map(t=>t.division).filter(Boolean))];$('#filters').classList.toggle('hidden',!all.length);$('#filters').innerHTML=groups.map(g=>`<button class="chip ${mlbFilter===g?'active':''}" data-filter="${g}">${g==='all'?'全地区':g}</button>`).join('');$$('#filters button').forEach(b=>b.onclick=()=>{mlbFilter=b.dataset.filter;renderBaseball()});const ts=mlbFilter==='all'?all:all.filter(t=>t.division===mlbFilter);$('#thead').innerHTML='<tr><th class="pos">順位</th><th class="team">チーム</th><th>試合</th><th>勝</th><th>敗</th><th>勝率</th><th>ゲーム差</th><th class="optional">リーグ</th><th class="optional">地区</th></tr>';$('#tbody').innerHTML=ts.map(t=>`<tr class="${t.rank<=3?'top3':''}"><td class="pos">${t.rank}</td><td class="team"><span class="team-cell">${logo(t)}${t.name}</span></td><td>${t.played}</td><td>${t.won}</td><td>${t.lost}</td><td class="points">${t.pct}</td><td>${t.gb}</td><td class="optional">${t.league}</td><td class="optional">${t.division}</td></tr>`).join('')||'<tr><td colspan="9">最新順位を取得できませんでした</td></tr>';}
function setFavorite(){const fs=JSON.parse(localStorage.getItem('wt-favorites')||'[]'),on=fs.includes(selected.id);$('#favorite').classList.toggle('on',on);$('#favorite').textContent=on?'★ お気に入り':'☆ お気に入り';}
$('#favorite').onclick=()=>{let fs=JSON.parse(localStorage.getItem('wt-favorites')||'[]');fs=fs.includes(selected.id)?fs.filter(x=>x!==selected.id):[...fs,selected.id];localStorage.setItem('wt-favorites',JSON.stringify(fs));setFavorite();renderQuick()};
$('#back').onclick=()=>{$('#standings').classList.add('hidden');$('.browser').classList.remove('hidden')};$$('.sport-card').forEach(b=>b.onclick=()=>{sport=b.dataset.sport;$$('.sport-card').forEach(x=>x.classList.toggle('active',x===b));$('#standings').classList.add('hidden');$('.browser').classList.remove('hidden');renderLeagues()});
$('#theme').onclick=()=>{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'';localStorage.setItem('wt-theme',dark?'dark':'light')};if(localStorage.getItem('wt-theme')==='dark')document.documentElement.dataset.theme='dark';renderLeagues();renderQuick();
