import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..'),now='2026-08-15T21:00:00.000Z';
const sets={
j1:['鹿島アントラーズ','柏レイソル','浦和レッズ','京都サンガF.C.','サンフレッチェ広島','ヴィッセル神戸','川崎フロンターレ','FC町田ゼルビア','ガンバ大阪','セレッソ大阪','ファジアーノ岡山','アビスパ福岡','FC東京','清水エスパルス','東京ヴェルディ','名古屋グランパス','横浜F・マリノス','湘南ベルマーレ','アルビレックス新潟','横浜FC'],
pl:['Arsenal','Manchester City','Liverpool','Chelsea','Newcastle United','Manchester United','Tottenham Hotspur','Aston Villa','Brighton','Brentford','Crystal Palace','Fulham','Everton','West Ham United','Bournemouth','Wolverhampton','Nottingham Forest','Leeds United','Burnley','Sunderland'],
laliga:['Real Madrid','Barcelona','Atlético Madrid','Athletic Club','Villarreal','Real Betis','Real Sociedad','Valencia','Sevilla','Girona','Celta Vigo','Osasuna','Getafe','Rayo Vallecano','Mallorca','Espanyol','Alavés','Levante','Elche','Real Oviedo'],
seriea:['Inter','Napoli','Juventus','AC Milan','Roma','Atalanta','Lazio','Fiorentina','Bologna','Torino','Genoa','Udinese','Como','Parma','Cagliari','Lecce','Verona','Sassuolo','Pisa','Cremonese'],
bundesliga:['Bayern München','Bayer Leverkusen','Borussia Dortmund','RB Leipzig','Eintracht Frankfurt','Freiburg','Stuttgart','Mainz 05','Werder Bremen','Borussia M’gladbach','Wolfsburg','Augsburg','Union Berlin','Hoffenheim','St. Pauli','Hamburger SV','Köln','Heidenheim'],
ligue1:['Paris Saint-Germain','Marseille','Monaco','Lille','Lyon','Nice','Strasbourg','Lens','Brest','Toulouse','Auxerre','Rennes','Nantes','Angers','Le Havre','Paris FC','Lorient','Metz'],
mls:['Inter Miami','FC Cincinnati','Columbus Crew','New York City FC','Philadelphia Union','Orlando City','Nashville SC','New York Red Bulls','Charlotte FC','Atlanta United','New England Revolution','Chicago Fire','D.C. United','CF Montréal','LAFC','LA Galaxy','Seattle Sounders','Portland Timbers','Minnesota United','Real Salt Lake','Colorado Rapids','Vancouver Whitecaps','Houston Dynamo','Austin FC','FC Dallas','St. Louis City','Sporting Kansas City','San Jose Earthquakes','San Diego FC']};
const seasons={j1:'2026 シーズン',pl:'2026-27 シーズン',laliga:'2026-27 シーズン',seriea:'2026-27 シーズン',bundesliga:'2026-27 シーズン',ligue1:'2026-27 シーズン',mls:'2026 シーズン'};
for(const [id,names] of Object.entries(sets)){const teams=names.map((name,i)=>{const played=id==='j1'||id==='mls'?26:0,won=Math.max(0,Math.floor((names.length-i)*.55)),draw=played?i%6:0,lost=Math.max(0,played-won-draw),gf=played?Math.max(8,50-i*2):0,ga=played?20+i:0;return{rank:i+1,name,logo:`https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=f0f5fa&color=153b64&bold=true&size=64`,played,won,draw,lost,gf,ga,gd:gf-ga,points:won*3+draw,movement:i%7===0?1:i%9===0?-1:0}});fs.writeFileSync(path.join(root,'data',`${id}.json`),JSON.stringify({league:id,season:seasons[id],updatedAt:now,source:'初期サンプルデータ（自動更新後に公式APIデータへ置換）',relegation:id==='mls'?0:id==='bundesliga'?2:3,teams},null,2));}
const divs=['ア・リーグ東','ア・リーグ中','ア・リーグ西','ナ・リーグ東','ナ・リーグ中','ナ・リーグ西'];const mlbNames=['New York Yankees','Boston Red Sox','Toronto Blue Jays','Baltimore Orioles','Tampa Bay Rays','Detroit Tigers','Cleveland Guardians','Minnesota Twins','Kansas City Royals','Chicago White Sox','Houston Astros','Seattle Mariners','Texas Rangers','Los Angeles Angels','Oakland Athletics','Philadelphia Phillies','New York Mets','Atlanta Braves','Miami Marlins','Washington Nationals','Chicago Cubs','Milwaukee Brewers','Cincinnati Reds','St. Louis Cardinals','Pittsburgh Pirates','Los Angeles Dodgers','San Diego Padres','San Francisco Giants','Arizona Diamondbacks','Colorado Rockies'];const mlb=mlbNames.map((name,i)=>{const won=74-(i%5)*5,lost=48+(i%5)*5;return{rank:i%5+1,name,logo:`https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=f0f5fa&color=153b64&bold=true&size=64`,played:won+lost,won,lost,pct:(won/(won+lost)).toFixed(3).replace(/^0/,''),gb:i%5===0?'—':((i%5)*5).toFixed(1),league:i<15?'American League':'National League',division:divs[Math.floor(i/5)]}});fs.writeFileSync(path.join(root,'data','mlb.json'),JSON.stringify({league:'mlb',season:'2026 レギュラーシーズン',updatedAt:now,source:'MLB Stats API',teams:mlb},null,2));
