import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..'),dataDir=path.join(root,'data'),key=process.env.API_FOOTBALL_KEY;
const config={j1:98,pl:39,laliga:140,seriea:135,bundesliga:78,ligue1:61,mls:253};
const japan=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric'}).format(new Date());
function previous(id){try{return JSON.parse(fs.readFileSync(path.join(dataDir,`${id}.json`),'utf8'))}catch{return null}}
function save(id,value){fs.writeFileSync(path.join(dataDir,`${id}.json`),JSON.stringify(value,null,2)+'\n')}
function fail(id,e){const old=previous(id);if(old){old.stale=true;old.lastErrorAt=new Date().toISOString();save(id,old)}console.error(`${id}: ${e.message}`)}
async function football(id,league){if(!key)throw new Error('API_FOOTBALL_KEY is not set');const season=id==='j1'||id==='mls'?Number(japan):Number(japan)-1;const r=await fetch(`https://v3.football.api-sports.io/standings?league=${league}&season=${season}`,{headers:{'x-apisports-key':key}});if(!r.ok)throw new Error(`API-FOOTBALL ${r.status}`);const json=await r.json(),rows=json.response?.[0]?.league?.standings?.[0];if(!rows?.length)throw new Error('standings are empty');const old=previous(id),oldRanks=new Map((old?.teams||[]).map(t=>[t.name,t.rank]));save(id,{league:id,season:`${season}${id==='j1'||id==='mls'?'':'-'+String(season+1).slice(-2)} シーズン`,updatedAt:new Date().toISOString(),source:'API-FOOTBALL',relegation:id==='mls'?0:id==='bundesliga'?2:3,teams:rows.map(x=>({rank:x.rank,name:x.team.name,logo:x.team.logo,played:x.all.played,won:x.all.win,draw:x.all.draw,lost:x.all.lose,gf:x.all.goals.for,ga:x.all.goals.against,gd:x.goalsDiff,points:x.points,movement:oldRanks.has(x.team.name)?oldRanks.get(x.team.name)-x.rank:0}))})}
async function baseball(){const season=Number(japan),url=`https://statsapi.mlb.com/api/v1/standings?leagueId=103,104&season=${season}&standingsTypes=regularSeason&hydrate=team` ,r=await fetch(url);if(!r.ok)throw new Error(`MLB Stats API ${r.status}`);const json=await r.json(),teams=[];for(const rec of json.records||[]){rec.teamRecords.forEach((x,i)=>teams.push({rank:i+1,name:x.team.name,logo:`https://www.mlbstatic.com/team-logos/${x.team.id}.svg`,played:x.gamesPlayed,won:x.wins,lost:x.losses,pct:x.winningPercentage,gb:x.gamesBack==='-'?'—':x.gamesBack,league:rec.league.name,division:rec.division.name}))}if(!teams.length)throw new Error('standings are empty');save('mlb',{league:'mlb',season:`${season} レギュラーシーズン`,updatedAt:new Date().toISOString(),source:'MLB Stats API',teams})}
for(const [id,league] of Object.entries(config)){try{await football(id,league)}catch(e){fail(id,e)}}try{await baseball()}catch(e){fail('mlb',e)}
